# ----- ENABLED -----

AccessModifierIndentation:
  Enabled: true
  EnforcedStyle: outdent

Alias:
  Enabled: true

AndOr:
  Enabled: true

AssignmentInCondition:
  Enabled: true

Blocks:
  Enabled: true

CaseEquality:
  Enabled: true

TrailingBlankLines:
  Enabled: true

TrailingWhitespace:
  Enabled: true



# ----- DISABLED -----

# Ruby 1.8 compatibility is required.
HashSyntax:
  Enabled: false

# Mostly long hardcoded strings which I’d rather not break up.
LineLength:
  Enabled: false

# Parameters are indented one soft tab instead.
AlignParameters:
  Enabled: false

# We should embrace UTF-8, not avoid it. Since the Encoding cop is enabled,
# there’s no point in enforcing ASCII comments.
AsciiComments:
  Enabled: false

# Hash parameters should not have braces, but this cop is unable to distinguish
# between has parameters and methods that take a hash as a param.
BracesAroundHashParameters:
  Enabled: false

# This does not accomodate for code such as
#
# foo = case blah
#   when x
#     …
#   end
CaseIndentation:
  Enabled: false

# Personal convention is to use “memo” and an appropriate name for the element.
SingleLineBlockParams:
  Enabled: false



# ----- TO ENABLE LATER -----

ClassLength:
  Enabled: false

ClassVars:
  Enabled: false

CollectionMethods:
  Enabled: false

ColonMethodCall:
  Enabled: false

CommentAnnotation:
  Enabled: false

ConstantName:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

DefWithoutParentheses:
  Enabled: false

Documentation:
  Enabled: false

DotPosition:
  Enabled: false

EmptyLineBetweenDefs:
  Enabled: false

EmptyLinesAroundBody:
  Enabled: false

EmptyLiteral:
  Enabled: false

EndAlignment:
  Enabled: false

Eval:
  Enabled: false

EvenOdd:
  Enabled: false

FavorSprintf:
  Enabled: false

FavorUnlessOverNegatedIf:
  Enabled: false

HandleExceptions:
  Enabled: false

HashMethods:
  Enabled: false

IfUnlessModifier:
  Enabled: false

IndentationWidth:
  Enabled: false

Lambda:
  Enabled: false

MethodLength:
  Enabled: false

MethodName:
  Enabled: false

MultilineBlockChain:
  Enabled: false

MultilineTernaryOperator:
  Enabled: false

NestedTernaryOperator:
  Enabled: false

OpMethod:
  Enabled: false

ParenthesesAroundCondition:
  Enabled: false

PerlBackrefs:
  Enabled: false

Proc:
  Enabled: false

RaiseArgs:
  Enabled: false

RedundantBegin:
  Enabled: false

RedundantException:
  Enabled: false

RedundantReturn:
  Enabled: false

RedundantSelf:
  Enabled: false

RegexpLiteral:
  Enabled: false

RescueException:
  Enabled: false

RescueModifier:
  Enabled: false

ShadowingOuterLocalVariable:
  Enabled: false

SignalException:
  Enabled: false

SingleLineMethods:
  Enabled: false

SpaceAfterComma:
  Enabled: false

SpaceAfterNot:
  Enabled: false

SpaceAroundBlockBraces:
  Enabled: false

SpaceAroundEqualsInParameterDefault:
  Enabled: false

SpaceAroundOperators:
  Enabled: false

SpaceInsideBrackets:
  Enabled: false

SpaceInsideHashLiteralBraces:
  Enabled: false

SpaceInsideParens:
  Enabled: false

SpecialGlobalVars:
  Enabled: false

StringLiterals:
  Enabled: false

Syntax:
  Enabled: false

TrivialAccessors:
  Enabled: false

UnlessElse:
  Enabled: false

UselessAssignment:
  Enabled: false

WordArray:
  Enabled: false
