language: ruby
rvm:
  - 2.2.3
  - 2.3.1
  - ruby-head
branches:
  only:
    - "master"
    - "/^release-/"
before_install: gem install bundler
matrix:
  include:
    - rvm: jruby-9.0.5.0
      env: DISABLE_NOKOGIRI=1
    - rvm: jruby-9.0.5.0
      env: DISABLE_NOKOGIRI=0
  allow_failures:
    - rvm: jruby-9.0.5.0
      env: DISABLE_NOKOGIRI=1
    - rvm: jruby-9.0.5.0
      env: DISABLE_NOKOGIRI=0
    - rvm: ruby-head
notifications:
  irc:
    channels:
      - "chat.freenode.net#nanoc"
    template:
      - "%{repository}/%{branch} %{commit} %{author}: %{message}"
    use_notice: true
    skip_join: true
cache: bundler
sudo: false
git:
  depth: 10
