language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - jruby-18mode
  - jruby-1.7.11
  - rbx-2.2.6
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-1.7.11
    - rvm: rbx-2.2.6
    - rvm: 1.8.7
notifications:
  irc:
    channels:
      - "chat.freenode.net#nanoc"
    template:
      - "%{repository}/%{branch} %{commit} %{author}: %{message}"
    use_notice: true
    skip_join: true
